image: debian:stable-slim

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2

stages:
  - test

tester:
  stage: test
  image: node:16
  script:
    - npm ci
    - npm run test

linter:
  stage: test
  image: node:16
  script:
    - npm ci
    - npm run eslint
